// SPDX-License-Identifier: AGPL-3.0-only
import { z } from "zod";
import { uuidSchema, datetimeSchema, userRefSchema, userRefWithAvatarSchema, paginationRequestSchema } from "./common.js";
import { tiptapContentSchema } from "./document.js";

export const workOrderStatusSchema = z.enum(["backlog", "ready", "in_progress", "in_review", "done"]);
export const phaseListItemSchema = z.object({ id: uuidSchema, name: z.string(), description: z.string().nullable(), sortOrder: z.number().int(), workOrderCount: z.number().int(), createdAt: datetimeSchema });
export const createPhaseRequestSchema = z.object({ name: z.string().min(1).max(255), description: z.string().max(2000).optional() });
export const updatePhaseRequestSchema = z.object({ name: z.string().min(1).max(255).optional(), description: z.string().max(2000).optional(), sortOrder: z.number().int().optional() });
export const workOrderListItemSchema = z.object({ id: uuidSchema, title: z.string(), status: workOrderStatusSchema, phase: z.object({ id: uuidSchema, name: z.string() }).nullable(), feature: z.object({ id: uuidSchema, name: z.string() }).nullable(), assignees: z.array(userRefWithAvatarSchema), deliverableType: z.string().nullable(), sortOrder: z.number().int(), createdAt: datetimeSchema, updatedAt: datetimeSchema });
export const workOrderDetailSchema = z.object({ id: uuidSchema, title: z.string(), status: workOrderStatusSchema, phase: z.object({ id: uuidSchema, name: z.string() }).nullable(), feature: z.object({ id: uuidSchema, name: z.string() }).nullable(), assignees: z.array(userRefWithAvatarSchema), description: tiptapContentSchema.nullable(), acceptanceCriteria: tiptapContentSchema.nullable(), outOfScope: tiptapContentSchema.nullable(), implementationPlan: tiptapContentSchema.nullable(), deliverableType: z.string().nullable(), sortOrder: z.number().int(), graphConnections: z.array(z.object({ nodeId: uuidSchema, entityType: z.string(), entityId: uuidSchema, label: z.string(), edgeType: z.string() })), createdBy: userRefSchema.nullable(), createdAt: datetimeSchema, updatedAt: datetimeSchema });
export const createWorkOrderRequestSchema = z.object({ title: z.string().min(1).max(500), phaseId: uuidSchema.optional(), featureId: uuidSchema.optional(), status: z.enum(["backlog", "ready"]).optional(), description: tiptapContentSchema.optional(), acceptanceCriteria: tiptapContentSchema.optional(), outOfScope: tiptapContentSchema.optional(), implementationPlan: tiptapContentSchema.optional(), assigneeIds: z.array(uuidSchema).optional(), deliverableType: z.string().max(100).optional() });
export const updateWorkOrderRequestSchema = z.object({ title: z.string().min(1).max(500).optional(), status: workOrderStatusSchema.optional(), phaseId: uuidSchema.nullable().optional(), featureId: uuidSchema.nullable().optional(), description: tiptapContentSchema.optional(), acceptanceCriteria: tiptapContentSchema.optional(), outOfScope: tiptapContentSchema.optional(), implementationPlan: tiptapContentSchema.optional(), assigneeIds: z.array(uuidSchema).optional(), deliverableType: z.string().max(100).optional(), sortOrder: z.number().int().optional() });
export const bulkUpdateWorkOrdersRequestSchema = z.object({ workOrderIds: z.array(uuidSchema).min(1).max(100), updates: z.object({ status: workOrderStatusSchema.optional(), phaseId: uuidSchema.nullable().optional(), assigneeIds: z.array(uuidSchema).optional(), deliverableType: z.string().max(100).optional() }) });
export const reorderWorkOrderRequestSchema = z.object({ workOrderId: uuidSchema, targetPhaseId: uuidSchema.nullable(), afterWorkOrderId: uuidSchema.nullable() });
export const listWorkOrdersQuerySchema = paginationRequestSchema.extend({ status: z.string().optional(), phaseId: uuidSchema.optional(), featureId: uuidSchema.optional(), assigneeId: uuidSchema.optional(), deliverableType: z.string().optional(), search: z.string().optional(), sortBy: z.enum(["sortOrder", "createdAt", "updatedAt"]).optional() });
